### ISSUE TITLE
Tooltip stamina use and actual stamina use discrepancy.

### ISSUE THREAD

**Issue by Lamphobic** [immortalityidle/immortalityidle.github.io#2]
In src/app/game-state/activity.service.ts the following activities have discrepancies between the tooltip listed stamina use and the stamina use in code.

MakeScaffold
line 545: 1000 vs line 549: 100

Smelting
line 1587: 30 vs line 1589: 20

**Comment by immortalityidle** [comment]
Fixed. Good catch.

**Comment by Lamphobic** [comment]
@immortalityidle 

Not fixed fully. MakeScaffold wasn't addressed. (also linking the relevant commit 0b4ba51)
